version: '2.1'
services:
  image:
    extends:
      file: docker-compose-base.yml
      service: base-zipkin-dependencies
    container_name: ${CONTAINER_HOST_NAME:-zipkin-dependencies}
    hostname: ${CONTAINER_HOST_NAME:-zipkin-dependencies}
    environment:
    - STORAGE_TYPE=${STORAGE_TYPE:-elasticsearch}
    - ES_HOSTS=${ES_HOSTS:-http://192.168.1.108:9202}
    restart: always
    volumes:
    - data:/data

networks:
  local-network:
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.18.0.0/16

volumes:
  data:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/data
      o: bind
